on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  inspect-code:
    name: Inspect code
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 2
      - name: Set up Node.js
        uses: actions/setup-node@v3.5.1
        with:
          cache: npm
          node-version: latest
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Test code
        run: npm run test